name: First Interaction Response

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  response:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello! :wave: Thank you for creating this issue.

            This is a multi-line comment with GitHub **Markdown** formatting:
            - You can use **bold** and *italic* text.
            - Add links, like [create-or-update-comment][1].
            - Include emoji :sparkles: to make your message more engaging.

            [1]: https://github.com/peter-evans/create-or-update-comment

            Don't hesitate to provide more details or ask questions if needed.

            :+1: If you find this helpful!

          reactions: '+1'

      - name: Close Pull Request
        if: github.event_name == 'pull_request_target'
        run: |
          # Add your logic here to close the pull request.
          # For example, you can use GitHub API or other actions to close it.
