name: Label Triggered Workflow

on:
  issues:
    types:
      - labeled

  pull_request_target:
    types:
      - labeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1

  automate_invite:
    if: contains(github.event.issue.labels.*.name, 'issue/invite')
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: layer5io
          label: issue/invite
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: "We are sending you an invitation to join the Layer5 GitHub Organization. :partying_face: <b>Welcome to the community! 🎉</b><br /><br />&nbsp;&nbsp;&nbsp;Be sure to :star: [star the projects](../stargazers), if you haven't already.<br />"
        env:
          INVITE_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}
  automate_Comment_On_issue_Valid:
    if: contains(github.event.issue.labels.*.name, 'issue/valid')
    runs-on: ubuntu-latest
    steps:
      - name: Comment  on Valid issue
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: layer5io
          label: issue/invite
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: "We are sending you an invitation to join the Layer5 GitHub Organization. :partying_face: <b>Welcome to the community! 🎉</b><br /><br />&nbsp;&nbsp;&nbsp;Be sure to :star: [star the projects](../stargazers), if you haven't already.<br />"
        env:
          INVITE_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}
